language: node_js
node_js: 12
cache: npm
script: npx gatsby build --prefix-paths
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  on:
    branch: master